-- CREATE DATABASE IF NOT EXISTS `toggl`;

-- CREATE USER IF NOT EXISTS 'toggle_user'@'localhost' IDENTIFIED BY '1B6ED928C37FB88C89299B0E799025D0';
-- GRANT ALL ON * TO 'toggle_user'@'localhost';
-- FLUSH PRIVILEGES;

-- USE toggl;